#!/bin/bash
echo ">> EJERCICIO 1: Workflow basico de CI"
echo ""
echo "Crea un archivo .github/workflows/ci.yml que:"
echo "  - Se active en push y pull_request a main"
echo "  - Use ubuntu-latest"
echo "  - Configure Python 3.11"
echo "  - Instale dependencias (pip install -r requirements.txt)"
echo "  - Ejecute tests (pytest)"
echo ""
echo "PISTA: on, jobs, runs-on, steps, actions/checkout, actions/setup-python"
echo ""
echo "========================================"
echo ""
echo ">> EJERCICIO 2: Workflow con matriz de versiones"
echo ""
echo "Amplia el workflow anterior para probar en Python 3.10, 3.11 y 3.12"
echo "usando una matriz (matrix)."
echo ""
echo "PISTA: strategy, matrix, python-version"
echo ""
echo "========================================"
echo ""
echo ">> EJERCICIO 3: Pipeline completo CI/CD"
echo ""
echo "Crea un workflow con dos jobs:"
echo "  - test: ejecuta los tests"
echo "  - deploy: solo si test pasa y el evento es push a main,"
echo "            ejecuta un paso que haga deploy (echo simulado)"
echo ""
echo "PISTA: needs, if, github.ref, github.event_name"
