#!/bin/bash
echo ">> SOLUCION EJERCICIO 1: Workflow basico de CI"
echo ""
echo "## Contenido de .github/workflows/ci.yml:"
echo "name: CI"
echo ""
echo "on:"
echo "  push:"
echo "    branches: [main]"
echo "  pull_request:"
echo "    branches: [main]"
echo ""
echo "jobs:"
echo "  test:"
echo "    runs-on: ubuntu-latest"
echo "    steps:"
echo "      - uses: actions/checkout@v4"
echo "      - uses: actions/setup-python@v5"
echo "        with:"
echo "          python-version: '3.11'"
echo "      - run: pip install -r requirements.txt"
echo "      - run: pytest"
echo ""
echo "========================================"
echo ""
echo ">> SOLUCION EJERCICIO 2: Workflow con matriz de versiones"
echo ""
echo "## Contenido de .github/workflows/ci-matrix.yml:"
echo "name: CI Matrix"
echo ""
echo "on: [push, pull_request]"
echo ""
echo "jobs:"
echo "  test:"
echo "    runs-on: ubuntu-latest"
echo "    strategy:"
echo "      matrix:"
echo "        python-version: ['3.10', '3.11', '3.12']"
echo "    steps:"
echo "      - uses: actions/checkout@v4"
echo "      - uses: actions/setup-python@v5"
echo "        with:"
echo "          python-version: \${{ matrix.python-version }}"
echo "      - run: pip install -r requirements.txt"
echo "      - run: pytest"
echo ""
echo "========================================"
echo ""
echo ">> SOLUCION EJERCICIO 3: Pipeline completo CI/CD"
echo ""
echo "## Contenido de .github/workflows/cd.yml:"
echo "name: CI/CD"
echo ""
echo "on:"
echo "  push:"
echo "    branches: [main]"
echo ""
echo "jobs:"
echo "  test:"
echo "    runs-on: ubuntu-latest"
echo "    steps:"
echo "      - uses: actions/checkout@v4"
echo "      - uses: actions/setup-python@v5"
echo "        with:"
echo "          python-version: '3.11'"
echo "      - run: pip install -r requirements.txt"
echo "      - run: pytest"
echo ""
echo "  deploy:"
echo "    needs: test"
echo "    runs-on: ubuntu-latest"
echo "    if: github.ref == 'refs/heads/main'"
echo "    steps:"
echo "      - run: echo 'Desplegando a produccion...'"
