#!/bin/bash
echo ">> EJERCICIO 1: Dockerfile propio"
echo ""
echo "Crea un Dockerfile para una aplicacion Python simple que:"
echo "  - Use python:3.11-slim como base"
echo "  - Copie un archivo app.py que imprima 'Hola Docker'"
echo "  - Instale dependencias de requirements.txt"
echo "  - Exponga el puerto 5000"
echo "  - Ejecute app.py al iniciar"
echo ""
echo "PISTA: FROM, COPY, RUN, EXPOSE, CMD"
echo ""
echo "Construye la imagen con: docker build -t mi-app ."
echo ""
echo "========================================"
echo ""
echo ">> EJERCICIO 2: Ejecutar con puertos y volumenes"
echo ""
echo "Ejecuta la imagen anterior mapeando:"
echo "  - Puerto 5000 del contenedor al 8080 del host"
echo "  - Un volumen del directorio actual a /app en el contenedor"
echo "  - Nombre del contenedor: mi-app-container"
echo "  - Modo detach (-d)"
echo ""
echo "PISTA: docker run -d -p 8080:5000 -v ... --name ..."
echo ""
echo "========================================"
echo ""
echo ">> EJERCICIO 3: Docker Compose con dos servicios"
echo ""
echo "Crea un archivo docker-compose.yml con:"
echo "  - Servicio 'web': construye desde ., puerto 8080:5000"
echo "  - Servicio 'db': imagen postgres:15, variable POSTGRES_PASSWORD=secret"
echo "  - Red interna compartida"
echo ""
echo "PISTA: version, services, build, image, ports, environment"
echo ""
echo "Levanta con: docker compose up -d"
