#!/bin/bash
echo ">> SOLUCION EJERCICIO 1: Dockerfile propio"
echo ""
echo "## Contenido de Dockerfile:"
echo "FROM python:3.11-slim"
echo "WORKDIR /app"
echo "COPY app.py ."
echo "COPY requirements.txt ."
echo "RUN pip install -r requirements.txt"
echo "EXPOSE 5000"
echo 'CMD ["python", "app.py"]'
echo ""
echo "## Contenido de app.py:"
echo 'print("Hola Docker")'
echo ""
echo "## Construir:"
echo "docker build -t mi-app ."
echo ""
echo "========================================"
echo ""
echo ">> SOLUCION EJERCICIO 2: Ejecutar con puertos y volumenes"
echo ""
echo "docker run -d \\"
echo "  -p 8080:5000 \\"
echo "  -v \$(pwd):/app \\"
echo "  --name mi-app-container \\"
echo "  mi-app"
echo ""
echo "========================================"
echo ""
echo ">> SOLUCION EJERCICIO 3: Docker Compose con dos servicios"
echo ""
echo "## Contenido de docker-compose.yml:"
echo "services:"
echo "  web:"
echo "    build: ."
echo "    ports:"
echo "      - '8080:5000'"
echo "    depends_on:"
echo "      - db"
echo "  db:"
echo "    image: postgres:15"
echo "    environment:"
echo "      - POSTGRES_PASSWORD=secret"
echo ""
echo "## Levantar:"
echo "docker compose up -d"
