"""
SOLUCIONES - Arrays y Listas Enlazadas
Ejecuta: python soluciones.py [numero]

Uso:
  python soluciones.py    -> Menu de soluciones
  python soluciones.py 1  -> Solucion del ejercicio 1
"""

import sys

if sys.platform == "win32":
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

def solucion_1():
    print("=" * 50)
    print("SOLUCION - Ejercicio 1: Lista Simplemente Enlazada")
    print("=" * 50)
    print()
    print("Clase Node y SinglyLinkedList completa:")
    print()
    print("```python")
    print("class Node:")
    print("    def __init__(self, data):")
    print("        self.data = data")
    print("        self.next = None")
    print()
    print("class SinglyLinkedList:")
    print("    def __init__(self):")
    print("        self.head = None")
    print()
    print("    def insert(self, data):")
    print("        new_node = Node(data)")
    print("        if not self.head:")
    print("            self.head = new_node")
    print("            return")
    print("        curr = self.head")
    print("        while curr.next:")
    print("            curr = curr.next")
    print("        curr.next = new_node")
    print()
    print("    def delete(self, data):")
    print("        if not self.head: return")
    print("        if self.head.data == data:")
    print("            self.head = self.head.next")
    print("            return")
    print("        curr = self.head")
    print("        while curr.next:")
    print("            if curr.next.data == data:")
    print("                curr.next = curr.next.next")
    print("                return")
    print("            curr = curr.next")
    print()
    print("    def search(self, data):")
    print("        curr = self.head")
    print("        while curr:")
    print("            if curr.data == data:")
    print("                return True")
    print("            curr = curr.next")
    print("        return False")
    print()
    print("    def print_list(self):")
    print("        curr = self.head")
    print("        while curr:")
    print("            print(f'{curr.data} -> ', end='')")
    print("            curr = curr.next")
    print("        print('None')")
    print()
    print("# Prueba")
    print("ll = SinglyLinkedList()")
    print("ll.insert(1); ll.insert(2); ll.insert(3)")
    print("ll.print_list()   # 1 -> 2 -> 3 -> None")
    print("ll.delete(2)")
    print("ll.print_list()   # 1 -> 3 -> None")
    print("print(ll.search(3))  # True")
    print("```")
    print()
    print("Complejidades:")
    print("  insert: O(n) - recorre hasta el final")
    print("  delete: O(n) - busca el elemento")
    print("  search: O(n) - recorre linealmente")

def solucion_2():
    print("=" * 50)
    print("SOLUCION - Ejercicio 2: Lista Doblemente Enlazada")
    print("=" * 50)
    print()
    print("```python")
    print("class Node:")
    print("    def __init__(self, data):")
    print("        self.data = data")
    print("        self.prev = None")
    print("        self.next = None")
    print()
    print("class DoublyLinkedList:")
    print("    def __init__(self):")
    print("        self.head = None")
    print("        self.tail = None")
    print()
    print("    def append(self, data):")
    print("        new_node = Node(data)")
    print("        if not self.head:")
    print("            self.head = new_node")
    print("            self.tail = new_node")
    print("            return")
    print("        self.tail.next = new_node")
    print("        new_node.prev = self.tail")
    print("        self.tail = new_node")
    print()
    print("    def prepend(self, data):")
    print("        new_node = Node(data)")
    print("        if not self.head:")
    print("            self.head = new_node")
    print("            self.tail = new_node")
    print("            return")
    print("        self.head.prev = new_node")
    print("        new_node.next = self.head")
    print("        self.head = new_node")
    print()
    print("    def delete(self, data):")
    print("        curr = self.head")
    print("        while curr:")
    print("            if curr.data == data:")
    print("                if curr.prev:")
    print("                    curr.prev.next = curr.next")
    print("                else:")
    print("                    self.head = curr.next")
    print("                if curr.next:")
    print("                    curr.next.prev = curr.prev")
    print("                else:")
    print("                    self.tail = curr.prev")
    print("                return")
    print("            curr = curr.next")
    print()
    print("    def print_forward(self):")
    print("        curr = self.head")
    print("        while curr:")
    print("            print(f'{curr.data} <-> ', end='')")
    print("            curr = curr.next")
    print("        print('None')")
    print()
    print("    def print_backward(self):")
    print("        curr = self.tail")
    print("        while curr:")
    print("            print(f'{curr.data} <-> ', end='')")
    print("            curr = curr.prev")
    print("        print('None')")
    print("```")
    print()
    print("Ventaja: con head y tail, append y prepend son O(1).")
    print("La lista se puede recorrer en ambos sentidos.")

def solucion_3():
    print("=" * 50)
    print("SOLUCION - Ejercicio 3: Invertir lista enlazada")
    print("=" * 50)
    print()
    print("```python")
    print("def reverse_linked_list(head):")
    print("    prev = None")
    print("    current = head")
    print("    while current:")
    print("        next_node = current.next")
    print("        current.next = prev")
    print("        prev = current")
    print("        current = next_node")
    print("    return prev")
    print()
    print("# Demo")
    print("ll = SinglyLinkedList()")
    print("ll.insert(1); ll.insert(2); ll.insert(3); ll.insert(4)")
    print("ll.head = reverse_linked_list(ll.head)")
    print("ll.print_list()  # 4 -> 3 -> 2 -> 1 -> None")
    print("```")
    print()
    print("Explicacion grafica:")
    print("  Paso 1: None <- 1 -> 2 -> 3 -> 4")
    print("  Paso 2: None <- 1 <- 2 -> 3 -> 4")
    print("  Paso 3: None <- 1 <- 2 <- 3 -> 4")
    print("  Paso 4: None <- 1 <- 2 <- 3 <- 4")
    print()
    print("Complejidad: O(n) tiempo, O(1) espacio extra.")
    print("Este es un problema CLASICO en entrevistas tecnicas!")

def menu():
    while True:
        print()
        print("=" * 50)
        print("SOLUCIONES - Arrays y Listas Enlazadas")
        print("=" * 50)
        print("1. Lista Simplemente Enlazada")
        print("2. Lista Doblemente Enlazada")
        print("3. Invertir lista enlazada")
        print("0. Salir")
        print()

        opcion = input("Ver solucion: ")

        soluciones = {"1": solucion_1, "2": solucion_2, "3": solucion_3}

        if opcion in soluciones:
            soluciones[opcion]()
            input("Presiona ENTER para continuar...")
        elif opcion == "0":
            print("Sigue asi!")
            break
        else:
            print("Opcion invalida")

def main():
    args = sys.argv[1:]
    if args and args[0].isdigit():
        [solucion_1, solucion_2, solucion_3][int(args[0]) - 1]()
    else:
        menu()

if __name__ == "__main__":
    main()
