#!/bin/bash
echo ">> EJERCICIO 1: Crear rama y fusionar"
echo ""
echo "Crea un repositorio, haz dos commits en main, crea una rama"
echo "feature, haz un commit, y fusionala a main con --no-ff."
echo ""
echo "PISTA: git init, git add, git commit, git branch, git merge"
echo ""
echo "Ejecuta los comandos manualmente en tu terminal."
echo ""
echo "========================================"
echo ""
echo ">> EJERCICIO 2: Resolver conflicto"
echo ""
echo "Crea un repositorio. En main crea archivo.txt con 'Hola'. Commitea."
echo "Crea rama feature, cambia el archivo a 'Mundo'. Commitea."
echo "Vuelve a main, cambia el archivo a 'Hola mundo'. Commitea."
echo "Fusiona feature en main y resuelve el conflicto."
echo ""
echo "PISTA: git merge, editar archivo, git add, git commit"
echo ""
echo "Ejecuta los comandos manualmente en tu terminal."
echo ""
echo "========================================"
echo ""
echo ">> EJERCICIO 3: Rebase interactivo"
echo ""
echo "Crea un repositorio con 4 commits en main (commit1 a commit4)."
echo "Usa rebase interactivo para combinar los commits 2 y 3 en uno solo."
echo ""
echo "PISTA: git rebase -i HEAD~4, squash/fixup"
echo ""
echo "Ejecuta los comandos manualmente en tu terminal."
