#!/bin/bash
echo ">> SOLUCION EJERCICIO 1: Crear rama y fusionar"
echo ""
echo "mkdir repo1 && cd repo1"
echo "git init"
echo "echo 'commit1' > a.txt && git add a.txt && git commit -m 'Commit 1'"
echo "echo 'commit2' > b.txt && git add b.txt && git commit -m 'Commit 2'"
echo "git checkout -b feature"
echo "echo 'feature' > c.txt && git add c.txt && git commit -m 'Commit feature'"
echo "git checkout main"
echo "git merge --no-ff feature -m 'Merge feature'"
echo ""
echo "========================================"
echo ""
echo ">> SOLUCION EJERCICIO 2: Resolver conflicto"
echo ""
echo "mkdir repo2 && cd repo2 && git init"
echo "echo 'Hola' > archivo.txt && git add . && git commit -m 'Initial commit'"
echo "git checkout -b feature"
echo "echo 'Mundo' > archivo.txt && git add . && git commit -m 'Feature change'"
echo "git checkout main"
echo "echo 'Hola mundo' > archivo.txt && git add . && git commit -m 'Main change'"
echo "git merge feature  # CONFLICTO!"
echo "# Editar archivo.txt manualmente para dejar el texto deseado"
echo "git add archivo.txt"
echo "git commit -m 'Resuelve conflicto merge feature'"
echo ""
echo "========================================"
echo ""
echo ">> SOLUCION EJERCICIO 3: Rebase interactivo"
echo ""
echo "mkdir repo3 && cd repo3 && git init"
echo "for i in 1 2 3 4; do"
echo "  echo \"commit\$i\" > file\$i.txt"
echo "  git add . && git commit -m \"Commit \$i\""
echo "done"
echo "git rebase -i HEAD~4"
echo "# En el editor, cambiar 'pick' por 'squash' en los commits 2 y 3"
echo "# Guardar y editar el mensaje del commit combinado"
